# TODO: consider adding user-agent rotation later if realistic simulation is required
DEFAULT_HEADERS = {
    'User-Agent': 'ASimplePythonCrawler/1.0 (+http://example.com/botinfo)',  # good etiquette :-)
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Language': 'en-US,en;q=0.5',
    'Connection': 'keep-alive',
}

# default extensions to ignore, which can be supplanted by user-supplied blacklist
DEFAULT_BLACKLIST_EXTENSIONS = {
    '.css',
    '.js',
    '.json',
    '.xml',
    '.rss',
    '.atom',
    '.txt',
    '.webmanifest',
    '.pdf',
    '.doc',
    '.docx',
    '.xls',
    '.xlsx',
    '.ppt',
    '.pptx',
    '.zip',
    '.gz',
    '.rar',
    '.tar',
    '.7z',
    '.exe',
    '.dmg',
    '.iso',
    '.png',
    '.jpg',
    '.jpeg',
    '.gif',
    '.svg',
    '.webp',
    '.ico',
    '.bmp',
    '.mp4',
    '.avi',
    '.mov',
    '.wmv',
    '.mp3',
    '.wav',
    '.ogg',
    '.woff',
    '.woff2',
    '.ttf',
    '.otf',
    '.eot',
}
